#Movies
Movie.create(name: "The Hunger Games: Catching Fire", date: "2013-11-21 00:00:00", genre: "Action, Adventure, Sci-Fi", description: "Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a \"Victor's Tour\" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.", director: "Francis Lawrence", duration: "146 ")
Movie.create(name: "X-Men: First Class", date: "2011-06-02 00:00:00", genre: "Action, Adventure, Sci-Fi", description: "Before Charles Xavier and Erik Lensherr took the names Professor X and Magneto, they were two young men discovering their powers for the first time. Before they were archenemies, they were closest of friends, working together, with other Mutants (some familiar, some new), to stop the greatest threat the world has ever known. In the process, a rift between them opened, which began the eternal war between Magneto's Brotherhood and Professor X's X-MEN.", director: "Matthew Vaughn", duration: "132 ")
Movie.create(name: "The Fault in Our Stars", date:"2014-06-06 00:00:00",genre:"Drama", description: "Hazel and Gus are two teenagers who share an acerbic wit, a disdain for the conventional, and a love that sweeps them on a journey. Their relationship is all the more miraculous given that Hazel's other constant companion is an oxygen tank, Gus jokes about his prosthetic leg, and they met and fell in love at a cancer support group.", director: "Josh Boone", duration: 126)
Movie.create(name: "Sen to Chihiro no kamikakushi", date: "2003-07-20 00:00:00", genre: "Animation, Adventure, Family", description: "Chihiro and her parents are moving to a small Japanese town in the countryside, much to Chihiro's dismay. On the way to their new home, Chihiro's father makes a wrong turn and drives down a lonely one-lane road which dead-ends in front of a tunnel. Her parents decide to stop the car and explore the area. They go through the tunnel and find an abandoned amusement park on the other side, with its own little town. When her parents see a restaurant with great-smelling food but no staff, they decide to eat and pay later. However, Chihiro refuses to eat and decides to explore the theme park a bit more. She meets a boy named Haku who tells her that Chihiro and her parents are in danger, and they must leave immediately She runs to the restaurant and finds that her parents have turned into pigs. In addition, the theme park turns out to be a town inhabited by demons, spirits, and evil gods. At the center of the town is a bathhouse where these creatures go to relax. The owner of the bathhouse is...", director: "Hayao Miyazaki", duration: "125 ")
Movie.create(name: "Pulp Fiction", date: "1995-03-01 00:00:00", genre: "Crime, Drama, Thriller", description: "Jules Winnfield and Vincent Vega are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace. Wallace has also asked Vincent to take his wife Mia out a few days later when Wallace himself will be out of town. Butch Coolidge is an aging boxer who is paid by Wallace to lose his next fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents.", director: "Quentin Tarantino", duration: "154 ")
Movie.create(name: "The Matrix", date: "1999-03-31 00:00:00", genre: "Action, Adventure, Sci-Fi", description: "Thomas A. Anderson is a man living two lives. By day he is an average computer programmer and by night a hacker known as Neo. Neo has always questioned his reality, but the truth is far beyond his imagination. Neo finds himself targeted by the police when he is contacted by Morpheus, a legendary computer hacker branded a terrorist by the government. Morpheus awakens Neo to the real world, a ravaged wasteland where most of humanity have been captured by a race of machines that live off of the humans' body heat and electrochemical energy and who imprison their minds within an artificial reality known as the Matrix. As a rebel against the machines, Neo must return to the Matrix and confront the agents: super-powerful computer programs devoted to snuffing out Neo and the entire human rebellion.", director: "Andy Wachowski", duration: "136 ")
Movie.create(name: "Man of Steel", date: "2013-06-13 00:00:00", genre: "Action, Adventure, Fantasy", description: "A young boy learns that he has extraordinary powers and is not of this Earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.", director: "Zack Snyder", duration: "143 ")
Movie.create(name: "Yes Man", date: "2008-12-19 00:00:00", genre: "Comedy, Romance", description: "Carl Allen is at a standstill. No future... Until the day he enrolls into a personal development program based on a very simple idea: say yes to everything! Carl discovers with amazement the magical power of \"Yes\", and sees his professional and romantic life turned upside down overnight: an unexpected promotion and a new girlfriend. But he'll soon discover that better can be good's enemy, and that all opportunities shouldn't be taken.", director: "Peyton Reed", duration: "104 ")
Movie.create(name: "50 First Dates", date: "2004-08-12 00:00:00", genre: "Comedy, Romance", description: "Henry Roth lives in a Hawaiian paradise with the company of endless women with no strings attached. This is until he meets Lucy Whitmore. Both Henry and Lucy enjoy the company of each other and feel the start of a serious relationship occurring. Approaching Lucy the next day, Henry is confused when Lucy fails to recognize him. This is the moment Henry discovers that Lucy actually suffers from short term memory loss and can't remember each individual day. Henry won't let this stop him and is prepared to make her fall in love with him all over again, each and every day.", director: "Peter Segal", duration: "99 ")
Movie.create(name: "Thor: The Dark World", date: "2013-10-31 00:00:00", genre: "Action, Adventure, Fantasy", description: "Thousands of years ago, a race of beings known as Dark Elves tried to send the universe into darkness by using a weapon known as the Aether. But warriors from Asgard stop them but their leader Malekith escapes to wait for another opportunity. The warriors find the Aether and since it can't be destroyed, they try to hide it. In the present day, Jane Foster awaits the return of Thor but it's been two years. He's trying to bring peace to the nine realms. Jane discovers an anomaly similar to the one that brought Thor to Earth. She goes to investigate and finds a wormhole and is sucked into it. Thor wishes to return to Earth but his father, Odin refuses to let him. Thor learns from Heimdall, the one who can see into all of the realms that Jane disappeared. Thor then returns to Earth just as Jane returns. But when some policemen try to arrest her, some kind of energy repulses them. Thor then brings her to Asgard to find out what happened to her. When it happens again, they discovered that ...", director: "Alan Taylor", duration: "112 ")
Movie.create(name: "Iron Man 3", date: "2013-04-26 00:00:00", genre: "Action, Adventure, Fantasy", description: "Marvel's \"Iron Man 3\" pits brash-but-brilliant industrialist Tony Stark/Iron Man against an enemy whose reach knows no bounds. When Stark finds his personal world destroyed at his enemy's hands, he embarks on a harrowing quest to find those responsible. This journey, at every turn, will test his mettle. With his back against the wall, Stark is left to survive by his own devices, relying on his ingenuity and instincts to protect those closest to him. As he fights his way back, Stark discovers the answer to the question that has secretly haunted him: does the man make the suit or does the suit make the man?", director: "Shane Black", duration: "130 ")
Movie.create(name: "Spider-Man", date: "2002-05-16 00:00:00", genre: "Action, Fantasy", description: "Based on Marvel Comics' superhero character, this is a story of Peter Parker who is a nerdy high-schooler. He was orphaned as a child, bullied by jocks, and can't confess his crush for his stunning neighborhood girl Mary Jane Watson. To say his life is \"miserable\" is an understatement. But one day while on an excursion to a laboratory a runaway radioactive spider bites him... and his life changes in a way no one could have imagined. Peter acquires a muscle-bound physique, clear vision, ability to cling to surfaces and crawl over walls, shooting webs from his wrist ... but the fun isn't going to last. An eccentric millionaire Norman Osborn administers a performance enhancing drug on himself and his maniacal alter ego Green Goblin emerges. Now Peter Parker has to become Spider-Man and take Green Goblin to the task... or else Goblin will kill him. They come face to face and the war begins in which only one of them will survive at the end.", director: "Sam Raimi", duration: "121 ")
Movie.create(name: "Avatar", date: "2009-12-18 00:00:00", genre: "Action, Adventure, Fantasy", description: "When his brother is killed in a robbery, paraplegic Marine Jake Sully decides to take his place in a mission on the distant world of Pandora. There he learns of greedy corporate figurehead Parker Selfridge's intentions of driving off the native humanoid \"Na'vi\" in order to mine for the precious material scattered throughout their rich woodland. In exchange for the spinal surgery that will fix his legs, Jake gathers intel for the cooperating military unit spearheaded by gung-ho Colonel Quaritch, while simultaneously attempting to infiltrate the Na'vi people with the use of an \"avatar\" identity. While Jake begins to bond with the native tribe and quickly falls in love with the beautiful alien Neytiri, the restless Colonel moves forward with his ruthless extermination tactics, forcing the soldier to take a stand - and fight back in an epic battle for the fate of Pandora.", director: "James Cameron", duration: "162 ")
Movie.create(name: "Star Wars", date: "1977-11-07 00:00:00", genre: "Action, Adventure, Fantasy", description: "Part IV in George Lucas' epic, Star Wars: A New Hope opens with a Rebel ship being boarded by the tyrannical Darth Vader. The plot then follows the life of a simple farm boy, Luke Skywalker, as he and his newly met allies (Han Solo, Chewbacca, Obi-Wan Kenobi, C-3PO, R2-D2) attempt to rescue a Rebel leader, Princess Leia, from the clutches of the Empire. The conclusion is culminated as the Rebels, including Skywalker and flying ace Wedge Antilles make an attack on the Empire's most powerful and ominous weapon, the Death Star.", director: "George Lucas", duration: "121 ")
Movie.create(name: "Toy Story", date: "1995-11-22 00:00:00", genre: "Animation, Adventure, Comedy", description: "A little boy named Andy loves to be in his room, playing with his toys, especially his doll named \"Woody\". But, what do the toys do when Andy is not with them, they come to life. Woody believes that he has life (as a toy) good. However, he must worry about Andy's family moving, and what Woody does not know is about Andy's birthday party. Woody does not realize that Andy's mother gave him an action figure known as Buzz Lightyear, who does not believe that he is a toy, and quickly becomes Andy's new favorite toy. Woody, who is now consumed with jealousy, tries to get rid of Buzz. Then, both Woody and Buzz are now lost. They must find a way to get back to Andy before he moves without them, but they will have to pass through a ruthless toy killer, Sid Phillips.", director: "John Lasseter", duration: "81 ")
Movie.create(name: "Monsters, Inc.", date: "2001-11-02 00:00:00", genre: "Animation, Adventure, Comedy", description: "A city of monsters with no humans called Monstropolis centers around the city's power company, Monsters, Inc. The lovable, confident, tough, furry blue behemoth-like giant monster named James P. Sullivan (better known as Sulley) and his wisecracking best friend, short, green cyclops monster Mike Wazowski, discover what happens when the real world interacts with theirs in the form of a 2-year-old baby girl dubbed \"Boo\", who accidentally sneaks into the monster world with Sulley one night. And now it's up to Sulley and Mike to send Boo back in her door before anybody finds out, especially two evil villains such as Sulley's main rival as a scarer, chameleon-like Randall (a monster that Boo is very afraid of), who possesses the ability to change the color of his skin, and Mike and Sulley's boss Mr. Waternoose, the chairman and chief executive officer of Monsters, Inc.", director: "Pete Docter", duration: "92 ")
Movie.create(name: "How to Train Your Dragon", date: "2010-04-01 00:00:00", genre: "Animation, Adventure, Comedy", description: "Long ago up North on the Island of Berk, the young Viking, Hiccup, wants to join his town's fight against the dragons that continually raid their town. However, his macho father and village leader, Stoik the Vast, will not allow his small, clumsy, but inventive son to do so. Regardless, Hiccup ventures out into battle and downs a mysterious Night Fury dragon with his invention, but can't bring himself to kill it. Instead, Hiccup and the dragon, whom he dubs Toothless, begin a friendship that would open up both their worlds as the observant boy learns that his people have misjudged the species. But even as the two each take flight in their own way, they find that they must fight the destructive ignorance plaguing their world.", director: "Dean DeBlois", duration: "98 ")
Movie.create(name: "Up", date: "2009-05-29 00:00:00", genre: "Animation, Adventure, Comedy", description: "A young Carl Fredrickson meets a young adventure-spirited girl named Ellie. They both dream of going to a lost land in South America. 70 years later, Ellie has died. Carl remembers the promise he made to her. Then, when he inadvertently hits a construction worker, he is forced to go to a retirement home. But before they can take him, he and his house fly away. However, he has a stowaway aboard: an 8-year-old boy named Russell, who's trying to get an Assisting the Elderly badge. Together, they embark on an adventure, where they encounter talking dogs, an evil villain and a rare bird named Kevin.", director: "Pete Docter", duration: "96 ")
Movie.create(name: "Batman Begins", date: "2005-06-16 00:00:00", genre: "Action, Adventure, Crime", description: "When his parents were killed, millionaire playboy Bruce Wayne relocates to Asia when he is mentored by Henri Ducard and Ra's Al Ghul in how to fight evil. When learning about the plan to wipe out evil in Gotham City by Ducard, Bruce prevents this plan from getting any further and heads back to his home. Back in his original surroundings, Bruce adopts the image of a bat to strike fear into the criminals and the corrupt as the icon known as 'Batman'. But it doesn't stay quiet for long.", director: "Christopher Nolan", duration: "140 ")
Movie.create(name: "Sucker Punch", date: "2011-03-25 00:00:00", genre: "Action, Fantasy, Thriller", description: "A young girl (Baby Doll) is locked away in a mental asylum by her abusive stepfather where she will undergo a lobotomy in five days' time. Faced with unimaginable odds, she retreats to a fantastical world in her imagination where she and four other female inmates at the asylum, plot to escape the facility. The lines between reality and fantasy blur as Baby Doll and her four companions, as well as a mysterious guide, fight to retrieve the five items they need that will allow them to break free from their captors before it's too late...", director: "Zack Snyder", duration: "110 ")
Movie.create(name: "Kill Bill: Vol. 1", date: "2003-12-05 00:00:00", genre: "Action, Crime", description: "The lead character, called 'The Bride,' was a member of the Deadly Viper Assassination Squad, lead by her lover 'Bill.' Upon realizing she was pregnant with Bill's child, 'The Bride' decided to escape her life as a killer. She fled to Texas, met a young man, who, on the day of their wedding rehearsal was gunned down by an angry and jealous Bill (with the assistance of the Deadly Viper Assassination Squad). Four years later, 'The Bride' wakes from a coma, and discovers her baby is gone. She, then, decides to seek revenge upon the five people who destroyed her life and killed her baby. The saga of Kill Bill Volume I begins.", director: "Quentin Tarantino", duration: "111 ")
Movie.create(name: "Die Hard", date: "1988-07-22 00:00:00", genre: "Action, Thriller", description: "New York City Detective John McClane has just arrived in Los Angeles to spend Christmas with his wife. Unfortunatly, it is not going to be a Merry Christmas for everyone. A group of terrorists, led by Hans Gruber is holding everyone in the Nakatomi Plaza building hostage. With no way of anyone getting in or out, it's up to McClane to stop them all. All 12!", director: "John McTiernan", duration: "131 ")
Movie.create(name: "Lethal Weapon 3", date: "1992-05-15 00:00:00", genre: "Action, Crime, Thriller", description: "Martin Riggs finally meets his match in the form of Lorna Cole, a beautiful but tough policewoman. Together with Roger Murtaugh, his partner, the three attempt to expose a crooked former policeman and his huge arms racket. The crooked cop (Jack Travis) thwarts them at every turn, mainly by killing anyone who is about to talk, but Murtaugh has personal problems of his own as his family are brought into the equation.", director: "Richard Donner", duration: "118 ")
Movie.create(name: "Kick-Ass", date: "2010-09-09 00:00:00", genre: "Action, Comedy", description: "Dave Lizewski is an unnoticed high school student and comic book fan with a few friends and who lives alone with his father. His life is not very difficult and his personal trials not that overwhelming. However, one day he makes the simple decision to become a super-hero even though he has no powers or training.", director: "Matthew Vaughn", duration: "117 ")
Movie.create(name: "The Avengers", date: "2012-04-26 00:00:00", genre: "Action, Fantasy", description: "Nick Fury is director of S.H.I.E.L.D, an international peace keeping agency. The agency is a who's who of Marvel Super Heroes, with Iron Man, The Incredible Hulk, Thor, Captain America, Hawkeye and Black Widow. When global security is threatened by Loki and his cohorts, Nick Fury and his team will need all their powers to save the world from disaster.", director: "Joss Whedon", duration: "143 ")
Movie.create(name: "The Hobbit: An Unexpected Journey", date: "2012-12-13 00:00:00", genre: "Adventure, Fantasy", description: "Bilbo Baggins is swept into a quest to reclaim the lost Dwarf Kingdom of Erebor from the fearsome dragon Smaug. Approached out of the blue by the wizard Gandalf the Grey, Bilbo finds himself joining a company of thirteen dwarves led by the legendary warrior, Thorin Oakenshield. Their journey will take them into the Wild; through treacherous lands swarming with Goblins and Orcs, deadly Wargs and Giant Spiders, Shapeshifters and Sorcerers. Although their goal lies to the East and the wastelands of the Lonely Mountain first they must escape the goblin tunnels, where Bilbo meets the creature that will change his life forever ... Gollum. Here, alone with Gollum, on the shores of an underground lake, the unassuming Bilbo Baggins not only discovers depths of guile and courage that surprise even him, he also gains possession of Gollum's \"precious\" ring that holds unexpected and useful qualities ... A simple, gold ring that is tied to the fate of all Middle-earth in ways Bilbo cannot begin to ...", director: "Peter Jackson", duration: "169 ")
Movie.create(name: "Pacific Rim", date: "2013-07-11 00:00:00", genre: "Action, Adventure, Sci-Fi", description: "When monstrous creatures, known as Kaiju, started rising from the sea, a war began that would take millions of lives and consume humanity's resources for years on end. To combat the giant Kaiju, a special type of weapon was devised: massive robots, called Jaegers, which are controlled simultaneously by two pilots whose minds are locked in a neural bridge. But even the Jaegers are proving nearly defenseless in the face of the relentless Kaiju. On the verge of defeat, the forces defending mankind have no choice but to turn to two unlikely heroes - a washed up former pilot (Charlie Hunnam) and an untested trainee (Rinko Kikuchi) - who are teamed to drive a legendary but seemingly obsolete Jaeger from the past. Together, they stand as mankind's last hope against the mounting apocalypse.", director: "Guillermo del Toro", duration: "131 ")
Movie.create(name: "Harry Potter and the Deathly Hallows: Part 2", date: "2011-07-14 00:00:00", genre: "Adventure, Family, Fantasy", description: "The final chapter begins as Harry, Ron, and Hermione continue their quest of finding and destroying the Dark Lord's three remaining Horcruxes, the magical items responsible for his immortality. But as the mystical Deathly Hallows are uncovered, and Voldemort finds out about their mission, the biggest battle begins and life as they know it will never be the same again.", director: "David Yates", duration: "130 ")
Movie.create(name: "Harry Potter and the Sorcerer's Stone", date: "2001-11-29 00:00:00", genre: "Adventure, Family, Fantasy", description: "Harry Potter and the Philospher's Stone is the first film in the Harry Potter series based on the novels by J.K. Rowling. It is the tale of Harry Potter, an ordinary 11-year-old boy serving as a sort of slave for his aunt and uncle who learns that he is actually a wizard and has been invited to attend the Hogwarts School for Witchcraft and Wizardry. Harry is snatched away from his mundane existence by Hagrid, the grounds keeper for Hogwarts, and quickly thrown into a world completely foreign to both him and the viewer. Famous for an incident that happened at his birth, Harry makes friends easily at his new school. He soon finds, however, that the wizarding world is far more dangerous for him than he would have imagined, and he quickly learns that not all wizards are ones to be trusted.", director: "Chris Columbus", duration: "152 ")
Movie.create(name: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe", date: "2006-01-05 00:00:00", genre: "Adventure, Family, Fantasy", description: "When the Pevensie family are evacuated out to the country, they are unaware of the adventure they will encounter. During a game of hide and seek, the youngest daughter, Lucy (Henley) discovers a wardrobe which transports her to the land of Narnia. Covered in snow, Narnia is full of weird and wonderful creatures, but is watched over by the evil White Witch, Jadis (Swinton). When all four Pevensie children end up through the wardrobe, they discover that it was meant to be, as two daughters of Eve and two sons of Adam must join with the mighty lion, Aslan (Neeson) to defeat the evil White Witch.", director: "Andrew Adamson", duration: "143 ")

#Series
s1 = Serial.create(name: "Doctor Who", date: "2005-03-26 00:00:00", genre: "Adventure, Drama, Family", description: "The Doctor looks and seems human. He's handsome, wi...", director: nil, duration: nil)

s2 = Serial.create(name: "The O.C.", date: "2003-08-14 00:00:00", genre: " Comedy, Drama, Romance",description: "Ensemble drama revolving around the young adult com...", director: nil, duration: nil)

#season
se1 = Season.create(description: "The 2005 series constitutes a loose story arc, deal...", date: "2005-03-26", number: 1, serial: s1)
se2 = Season.create(description: "The first episode of the series, \"New Earth\", wasa...", date: "2006-04-15", number: 2, serial: s1)
se3 = Season.create(description: "The first season of The O.C. commenced airing in th...", date: "2003-08-05", number: 1, serial: s2)

#Episodes
Episode.create(name: "Rose", description: "Rose Tyler is just an ordinary shop worker living a...", date: "2005-03-26", number: 1, write: "Russell T Davies", director: "Keith Boak", duration: 45, season: se1)

Episode.create(name: "The End Of The World", description: "Rose goes off on her first adventure with the Docto...", date: "2005-04-02", number: 2, write: "Russell T Davies", director: "Euros Lyn", duration: 45, season: se1)

Episode.create(name: "The Unquiet Dead", description: "The Doctor has great expectations for his latest ad...", date: "2005-04-09", number: 3, write: "Mark Gatiss", director: "Euros Lyn", duration: 45,season: se1)

Episode.create(name: "Aliens of London", description: "The Doctor returns Rose to her own time - well, sor...", date: "2005-04-16", number: 4, write: "Russell T Davies", director: "Keith Boak", duration: 45, season: se1)

Episode.create(name: "World War Three", description: "The fiendish Slitheen have been unmasked as the one...", date: "2005-04-23", number: 5, write: "Russell T Davies", director: "Keith Boak", duration: 45, season: se1)

Episode.create(name: "New Earth", description: "As Rose Tyler embarks upon her first big TARDIS adv...", date: "2006-04-15", number: 1, write: "Russell T Davies", director: "James Hawes", duration: 45, season: se2)

Episode.create(name: "Tooth and Claw", description: "The Doctor and Rose are transported to 19th Century...", date: "2006-04-22", number: 2, write: "Russell T Davies", director: "Euros Lyn", duration: 45, season: se2)

Episode.create(name: "School Reunion", description: "The Krillitanes - aliens with a mix-and-match physi...", date: "2006-04-29", number: 3, write: "Toby Whithouse", director: "James Hawes", duration: 45, season: se3)

Episode.create(name: "Pilot", description: "After Ryan just escapes jail time and is kicked out...", date: "2003-08-05", number: 1, write: "Josh Schwartz", director: "Doug Liman", duration: 44, season: se3)

Episode.create(name: "The Model Home", description: "Marissa and Seth convince Ryan not to leave Newport...", date: "2003-08-12", number: 2, write: "Allan Heinberg, Josh Schwartz", director: "Doug Liman", duration: 44, season: se3)

Episode.create(name: "The Gamble", description: "Sandy comes to Ryan's rescue once again. Kirsten de...", date: "2003-08-19", number: 3, write: "Jane Espenson", director: "Ian Toynton", duration: 44, season: se3)

